### PR TITLE
configure cert auth for pulp

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
contains #27 and #29 for (obvious?) reasons :)

**Comment by evgeni** [comment]
huh, you can't tell `smart_proxy_pulp` which CA to use, so if the CA is not imported into the system store, things fail.
fun.

**Comment by evgeni** [comment]
:green_apple: 

keeping it draft as I think we shouldn't be using `nightly` images -- unless you're OK with that?

**Comment by ehelms** [comment]
> 🍏
> 
> keeping it draft as I think we shouldn't be using `nightly` images -- unless you're OK with that?

I'm OK with that.

**Review by ehelms — APPROVED** [review]

**Pull request merged**
